/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package http_work.main;

import http_work.util.HttpImageStatusCli;

public class App {
    public static void main(String[] args) {
        new HttpImageStatusCli().askStatus();
    }
}
